---
title: "GR5320 Project"
output: html_notebook
---


Step 1: Load Data
```{r,message=FALSE}
library(ggplot2)
library(quantmod)
```

```{r}
XOM <- read.csv("../data/XOM-bloomberg.csv")
INTC <- read.csv("../data/INTC-bloomberg.csv")
imp_vol <- read.csv("../data/volatility.csv")

XOM$Dates <- as.Date(XOM$Dates,"%m/%d/%Y")
INTC$Dates <- as.Date(INTC$Dates,"%m/%d/%Y")
imp_vol$Date <- as.Date(imp_vol$Date,"%m/%d/%Y")
```

Step 2: Source function and fiels 
```{r}
# calculate parameter for return
source("../code/parameter/winEstGBM.R")
source("../code/parameter/expEstGBM.R")

# historical VaR/ES
source("../code/stock/HVaR.R")
source("../code/stock/HES.R")

# monte carlo VaR/ES
# source("../code/stock/MCVAR & MCES.R")
source("../code/stock/MC_update.R")
source("../code/Put_MCVaR.R")

# Parametric VaR/ES
source("../code/stock/gbmVaR.R")
source("../code/stock/gbmES.R")
source("../code/parametricVaR.R")
source("../doc/calculation_measure.R")

# plot graph
source("../code/plotGraph.R")
```

Step 3: Individual Stock Analysis
#### 3.0: Prepara Inputs
```{r}
#price1 <- XOM$PX_LAST
#price2 <- INTC$PX_LAST
s1 <- XOM$PX_LAST
s2 <- INTC$PX_LAST
dRtn <- 5
year <- 5
par1 <- winEstGBM(s1,dRtn,year)
par2 <- winEstGBM(s2,dRtn,year)
s0<-10000
```

#### 3.1: Calculate Stock VaR
```{r}
# historical VaR  
Hvar <- HVaR_S(s1,0.99,dRtn,year,s0)
plotGraph(Hvar,XOM$Dates)


# paramentric VaR
Gvar <- gbmVaR(s0,par1$mu_gbm,par1$sigma_gbm,0.99,dRtn)
plotGraph(Gvar,XOM$Dates)


# Monte Carlo VaR
MVaR <- MCVaR(s0, par1$mu_gbm, par1$sigma_gbm, p, dt, npaths,years,dRtn)
plotGraph(MVaR,XOM$Dates)
```


Step 4: Portfolio Analysis
#### 4.0: Prepare Inputs
```{r}
# Parametric VaR (portfolio follow Normal Distribution)
#s1 <- XOM$PX_LAST
#s2 <- INTC$PX_LAST
s1_0 <- 32.0625 #XOM
s2_0 <- 25.0156 #INTC
mu1 <- par1$mu_gbm[1:7000]
mu2 <- par2$mu_gbm[1:7000]
sigma1 <- par1$sigma_gbm[1:7000]
sigma2 <- par2$sigma_gbm[1:7000]
a <- c(156,200)  # if we only assign weights to each component of portfolio? how to decide position here?
p_price <- cbind(s1,s2)
portfolio_price <- rep(0,length(mu1))
  for (i in 1:length(portfolio_price)){
    for (j in 1:length(a)){
      portfolio_price[i] <- a[j]*p_price[i,j]
    }
  }
s0 <- c(s1_0,s2_0)  # what's s1_0 and s2_0 here, is the dailty stock price?
v0 = FALSE
mu <- c(mu1,mu2)
sigma <- c(sigma1,sigma2)
datadt <- 1/252
rtn1 <- -diff(log(s1),1)
rtn2 <- -diff(log(s2),1)
rtn1 <- rtn1[1:7000]
rtn2 <- rtn2[1:7000]
rho <- cov(rtn1,rtn2)/datadt/(sigma1*sigma2)
t <- 5/252
p <- 0.99
```

#### 4.1: Calculate Portfolio VaR
##### 4.1.1: Portfolio only includes stocks
```{r}
# part1: portfolio = weight1*s1+weight2*s2
# Inputs Preparation
source("../code/portfolio_price.R")

prices <- comb.col(XOM$PX_LAST,INTC$PX_LAST)
wgt <- c(156/(156+200),200/(156+200))
positions <- c("long","long") 

dRtn <- 5
year <- 5
v0 <- 10000

portfolio_price <- portfolio_px(prices,wgt,positions,v0)
par_p <- winEstGBM(portfolio_price,dRtn,year)
```

```{r}
# Historical VaR 
port_Hvar <- HVaR_S(portfolio_price,0.99,dRtn,year,v0)
plotGraph(port_Hvar,INTC$Dates)

# Parametric VaR portfolio follows GBM
Gvar <- gbmVaR(v0,par_p$mu_gbm,par_p$sigma_gbm,0.99,dRtn)
plotGraph(Gvar,INTC$Dates)

# Parametric VaR underlying follows 
PVaR <- parametricVaR(a,s0,mu,sigma,rho,p,t)
plotGraph(PVaR,INTC$Dates)
```


##### 4.1.2: Portfolio includes stocks and options
```{r}
# portfolio includes stock + option
add.col<-function(df, new.col) {
  n.row<-dim(df)[1]
  length(new.col)<-n.row
  cbind(df, new.col)
}

colnames(imp_vol) <- c("Dates","PX","IMP_VOL")

imp_vol$Dates <- format(time(imp_vol$Dates))
INTC$Dates <- format(time(INTC$Dates))

merge(imp_vol,INTC[,c(1,6)],by= "Dates",all = T)

```











############################## Don't Run Below Parts #######################

#########################################################
Step:test part
```{r}
# package to load stock price
if (!require("quantmod")) {
    install.packages("quantmod")
    library(quantmod)
}
# Get me my beloved pipe operator!
if (!require("magrittr")) {
    install.packages("magrittr")
    library(magrittr)
}
```

```{r}
# one approach to load stock dataset
start <- as.Date("2010-01-01")
end <- as.Date("2018-10-01")

getSymbols("AAPL", src = "yahoo", from = start, to = end)
getSymbols(c("MSFT", "GOOG"), src = "yahoo", from = start, to = end)

aple <- Ad(getSymbols("AAPL", src = "yahoo", auto.assign= F, from = start))
intc <- Ad(getSymbols("INTC", src = "yahoo", auto.assign= F, from = start))

stocks <- as.xts(data.frame(AAPL = AAPL[, "AAPL.Close"], MSFT = MSFT[, "MSFT.Close"], 
    GOOG = GOOG[, "GOOG.Close"]))

# useful in plot
chartSeries(returns_AAPL)

```


